### ISSUE TITLE
Chat using socket.io

### ISSUE THREAD

**Issue by dnbailey** [SullivanNorthHS/snhs-r3c0n.github.io#1]
Found a good tutorial for using socket.io with express. Might give you a base to build on. [Socket.io Chat](https://socket.io/get-started/chat/)

**Comment by snhs-r3c0n** [comment]
@dnbailey Looks good, I can try adding login and/or nicknames to this.

**Comment by dnbailey** [comment]
Good idea. Nickname would be a doable addition. May want to save login as a later add-on, because it will require a database of some sort.

**Comment by snhs-r3c0n** [comment]
I am using this example to build upon, thank you for the recommendation. @dnbailey
