### ISSUE TITLE
Center tag deprecated

### ISSUE THREAD

**Issue by dnbailey** [SullivanNorthHS/snhs-r3c0n.github.io#2]
https://github.com/SullivanNorthHS/snhs-r3c0n.github.io/blob/34e468c9f8d7ef6c3c840be823c6ed8f647422a4/public/index.html#L45

This tag has been eliminated. Use css to center the text instead. You can target copyright class and make changes in CSS.

https://www.w3schools.com/tags/tag_center.asp

**Comment by snhs-r3c0n** [comment]
I will work to fix this. Current hold up is problems with the <p> tags not staying center when I apply text-align: center; to them.

**Comment by snhs-r3c0n** [comment]
I have removed the <center> tag completely from this program. Thank you for your issue!
