### ISSUE TITLE
Load libraries from CDN

### ISSUE THREAD

**Issue by dnbailey** [SullivanNorthHS/snhs-r3c0n.github.io#3]
https://github.com/SullivanNorthHS/snhs-r3c0n.github.io/blob/6e3c0978e7541e74bc6f6234244c6058ecd0de65/about.html#L9

Using a CDN can allow jquery to be loaded a bit faster, because it will load in parallel with the files served from local server.

[Jquery CDN](https://code.jquery.com/)

**Comment by snhs-r3c0n** [comment]
I will add that into the next push.
